import Link from 'next/link'
import { ContractorRoiCalculator } from './contractor-roi-calculator'

type Props = { locale?: 'en-US' | 'pt-BR' }

const enFaq = [
  ['What is a good marketing ROI for a contractor?', 'There is no universal benchmark. The right target depends on gross margin, sales cycle, attribution quality, and capacity. Compare channels using the same definitions and a consistent evaluation window.'],
  ['Should contractors measure ROI using revenue or profit?', 'Profit is usually the safer decision metric because revenue ignores delivery costs. Revenue-based ROI can be useful for top-line reporting, but gross-profit-based ROI better reflects economic return.'],
  ['What marketing costs should contractors include?', 'Include media spend, management fees, creative, landing pages, tracking, software, and other costs required to generate and convert the opportunity.'],
]
const ptFaq = [
  ['Qual é um bom ROI de marketing para contractors?', 'Não existe um benchmark universal. A meta depende da margem bruta, do ciclo de vendas, da qualidade da atribuição e da capacidade operacional. Compare canais com as mesmas definições e janela de análise.'],
  ['Contractors devem medir ROI usando receita ou lucro?', 'Lucro costuma ser o indicador mais seguro porque receita não considera custos de execução. ROI baseado em receita serve para reporting, mas o baseado em lucro bruto representa melhor o retorno econômico.'],
  ['Quais custos de marketing devem ser incluídos?', 'Inclua mídia, gestão, criativos, landing pages, tracking, softwares e todos os custos necessários para gerar e converter oportunidades.'],
]

export function ContractorRoiArticle({ locale = 'en-US' }: Props) {
  const pt = locale === 'pt-BR'
  const faq = pt ? ptFaq : enFaq
  const related = pt ? [
    ['/br/marketing-para-general-contractors', 'Marketing para General Contractors: O Guia Completo'],
    ['/br/blog/google-ads-para-general-contractors', 'Google Ads para General Contractors'],
    ['/br/blog/bom-custo-por-lead-para-general-contractors', 'Qual É um Bom Custo por Lead para General Contractors?'],
    ['/br/blog/como-fazer-follow-up-com-leads-de-contractors', 'Como Fazer Follow-Up com Leads de Contractors'],
  ] : [
    ['/general-contractor-marketing', 'Marketing for General Contractors: The Complete Guide'],
    ['/blog/google-ads-for-general-contractors', 'Google Ads for General Contractors'],
    ['/blog/good-cost-per-lead-for-general-contractors', 'What Is a Good Cost per Lead for General Contractors?'],
    ['/blog/how-to-follow-up-with-contractor-leads', 'How to Follow Up With Contractor Leads'],
  ]
  const title = pt ? 'Como Calcular o ROI de Marketing para General Contractors' : 'How to Calculate Contractor Marketing ROI'
  return <article className="mx-auto max-w-4xl px-5 py-12 md:px-8">
    <header className="mb-10 border-b border-[#D8E0EA] pb-8">
      <p className="mb-3 text-xs font-semibold uppercase tracking-[0.16em] text-[#1565D8]">{pt ? 'Métricas de marketing' : 'Marketing analytics'}</p>
      <h1 className="max-w-3xl text-4xl font-bold tracking-tight text-[#0A0A0A] md:text-5xl">{title}</h1>
      <p className="mt-5 max-w-3xl text-lg leading-8 text-[#667085]">{pt ? 'Aprenda a calcular o retorno real do investimento em marketing — do gasto com anúncios à receita assinada e ao lucro bruto.' : 'Learn how to calculate the real return on marketing investment — from ad spend to signed revenue and gross profit.'}</p>
    </header>
    <nav aria-label={pt ? 'Nesta página' : 'On this page'} className="mb-10 border border-[#D8E0EA] bg-[#F7F9FC] p-5"><p className="mb-3 text-sm font-semibold text-[#0A0A0A]">{pt ? 'Nesta página' : 'On this page'}</p><div className="grid gap-2 text-sm text-[#1565D8] md:grid-cols-2"><a href="#formula">{pt ? 'Fórmula de ROI' : 'ROI formula'}</a><a href="#funnel">{pt ? 'Funil de medição' : 'Measurement funnel'}</a><a href="#calculator">{pt ? 'Calculadora' : 'Calculator'}</a><a href="#checklist">{pt ? 'Checklist' : 'Checklist'}</a></div></nav>
    <div className="space-y-10 text-[17px] leading-8 text-[#344054]">
      <section><h2 className="mb-3 text-2xl font-bold text-[#0A0A0A]">{pt ? 'O que é ROI de marketing para contractors?' : 'What Is Contractor Marketing ROI?'}</h2><p>{pt ? 'ROI de marketing compara o valor econômico gerado por uma iniciativa com o investimento necessário para gerar esse resultado. Para uma empresa de construção, isso significa conectar campanhas a oportunidades qualificadas, projetos assinados, receita e margem — não apenas cliques ou leads.' : 'Marketing ROI compares the economic value generated by an initiative with the investment required to create that result. For a construction company, that means connecting campaigns to qualified opportunities, signed projects, revenue, and margin—not just clicks or leads.'}</p></section>
      <section id="formula"><h2 className="mb-3 text-2xl font-bold text-[#0A0A0A]">{pt ? 'Fórmula de ROI de marketing' : 'Contractor Marketing ROI Formula'}</h2><div className="my-5 border-l-4 border-[#1565D8] bg-[#F7F9FC] p-5 font-mono text-base">ROI = (Retorno − Investimento) ÷ Investimento × 100</div><p>{pt ? 'Quando o retorno é medido como lucro bruto, o cálculo é mais útil para decisões de orçamento: subtraia o investimento total de marketing do lucro bruto atribuído e divida pelo investimento.' : 'When return is measured as gross profit, the calculation is more useful for budget decisions: subtract total marketing investment from attributed gross profit and divide by investment.'}</p></section>
      <section><h2 className="mb-3 text-2xl font-bold text-[#0A0A0A]">{pt ? 'ROI de marketing vs. ROAS, CPL e CAC' : 'Marketing ROI vs. ROAS, Cost per Lead, and CAC'}</h2><p>{pt ? 'ROAS mede receita gerada por mídia. CPL mede o custo de uma oportunidade. CAC mede o custo de adquirir um cliente. ROI conecta esses indicadores ao lucro e aos custos completos, por isso deve ser usado para decisões econômicas.' : 'ROAS measures revenue generated by media. Cost per lead measures the cost of an opportunity. CAC measures the cost to acquire a customer. ROI connects these metrics to profit and full costs, so it is the better economic decision metric.'}</p></section>
      <section id="funnel"><h2 className="mb-3 text-2xl font-bold text-[#0A0A0A]">{pt ? 'O funil de medição para contractors' : 'The Contractor Marketing Measurement Funnel'}</h2><p>{pt ? 'Registre cada etapa: investimento, leads, leads qualificados, appointments, estimativas, projetos assinados, receita e lucro bruto. Sem essa cadeia, a atribuição tende a parar no formulário e não chega ao resultado comercial.' : 'Track every stage: investment, leads, qualified leads, appointments, estimates, signed projects, revenue, and gross profit. Without this chain, attribution stops at the form instead of reaching the commercial outcome.'}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{(pt ? ['Investimento', 'Leads qualificados', 'Estimativas', 'Projetos assinados', 'Receita', 'Lucro bruto'] : ['Marketing spend', 'Qualified leads', 'Estimates', 'Signed projects', 'Revenue', 'Gross profit']).map((item) => <div key={item} className="border border-[#D8E0EA] p-4 text-sm font-semibold text-[#0A0A0A]">{item}</div>)}</div></section>
      <section><h2 className="mb-3 text-2xl font-bold text-[#0A0A0A]">{pt ? 'Como calcular passo a passo' : 'How to Calculate ROI Step by Step'}</h2><ol className="list-decimal space-y-3 pl-6"><li>{pt ? 'Some mídia, gestão, tracking, criativos, software e outros custos.' : 'Add media, management, tracking, creative, software, and other costs.'}</li><li>{pt ? 'Conecte cada oportunidade ao canal e à campanha.' : 'Connect each opportunity to its channel and campaign.'}</li><li>{pt ? 'Registre projetos assinados e receita atribuída.' : 'Record signed projects and attributed revenue.'}</li><li>{pt ? 'Aplique a margem bruta para estimar lucro.' : 'Apply gross margin to estimate gross profit.'}</li><li>{pt ? 'Compare canais após uma janela de vendas suficiente.' : 'Compare channels after a sufficient sales window.'}</li></ol></section>
      <section id="calculator"><ContractorRoiCalculator locale={locale} /></section>
      <section><h2 className="mb-3 text-2xl font-bold text-[#0A0A0A]">{pt ? 'Diagnóstico de ROI baixo' : 'Diagnosing Low Contractor Marketing ROI'}</h2><p>{pt ? 'ROI baixo pode vir de tráfego inadequado, lead quality baixa, falhas de conversão, follow-up lento, problemas de vendas ou margem insuficiente. Não reduza orçamento antes de identificar em qual etapa o valor está vazando.' : 'Low ROI can come from poor traffic, weak lead quality, conversion problems, slow follow-up, sales issues, or insufficient margin. Do not cut budget before identifying where value is leaking.'}</p></section>
      <section id="checklist"><h2 className="mb-3 text-2xl font-bold text-[#0A0A0A]">{pt ? 'Checklist de ROI' : 'Contractor Marketing ROI Checklist'}</h2><ul className="list-disc space-y-2 pl-6">{(pt ? ['Defina receita e lucro bruto.', 'Inclua todos os custos de marketing.', 'Use CRM com origem e status.', 'Avalie por canal, serviço e localização.', 'Dê tempo para o ciclo de vendas fechar.'] : ['Define revenue and gross profit.', 'Include all marketing costs.', 'Use a CRM with source and status.', 'Evaluate by channel, service, and location.', 'Allow time for the sales cycle to close.']).map((item) => <li key={item}>{item}</li>)}</ul></section>
      <section><h2 className="mb-3 text-2xl font-bold text-[#0A0A0A]">{pt ? 'Perguntas frequentes' : 'Frequently Asked Questions'}</h2><div className="space-y-6">{faq.map(([question, answer]) => <div key={question}><h3 className="font-semibold text-[#0A0A0A]">{question}</h3><p className="mt-1">{answer}</p></div>)}</div></section>
      <section className="border-t border-[#D8E0EA] pt-8"><h2 className="mb-4 text-2xl font-bold text-[#0A0A0A]">{pt ? 'Continue aprendendo' : 'Continue learning'}</h2><div className="grid gap-3 md:grid-cols-2">{related.map(([href, label]) => <Link key={href} href={href} className="border border-[#D8E0EA] p-4 text-sm font-semibold text-[#1565D8] hover:bg-[#F7F9FC]">{label}</Link>)}</div></section>
    </div>
  </article>
}

export function getRoiFaq(locale: 'en-US' | 'pt-BR') { return locale === 'pt-BR' ? ptFaq : enFaq }
